services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - POSTGRESS_DB_HOST=db
      - POSTGRESS_DB_PORT=5432
      - POSTGRESS_DB_NAME=postgres
      - POSTGRESS_DB_USER=postgres
      - POSTGRESS_DB_PASSWORD=postgres
    depends_on:
      - db

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./sn_db_back.sql:/docker-entrypoint-initdb.d/sn_db_back.sql

volumes:
  postgres-data: